### ISSUE TITLE
C sets mass to 1

### ISSUE THREAD

**Issue by m-ender** [C0deH4cker/Fission#5]
I guess that makes sense since that's the starting value, but the docs currently say that it sets both mass and energy to zero.

**Comment by C0deH4cker** [comment]
The documentation is incorrect, thanks for spotting that! There may be other inconsistencies between documentation and implementation, unfortunately. In cases where they differ, the implementation is most likely the intended approach, and I just forgot to update the documentation to reflect these changes.

**Comment by C0deH4cker** [comment]
Fixed in 9b3d880c323badf66bdab908876ebea84c390aa9
