### ISSUE TITLE
v1 Branch for Tio

### ISSUE THREAD

**Issue by AndrewSav** [C0deH4cker/Fission#7]
I'm wondering if it's possible to host the v1 branch for TriItOnline in this repository, rather than on TIO's one.

Currently we have this branch in TIO repo:

https://github.com/TryItOnline/Fission/commits/v1

It has two additional commits as commits as compared to what's in this official repository:
- changes for the linux compilers not to choke on the sources
- memory corruption fix by Martin, which was eventually integrated in v2

These two things were needed to run v1 on TIO.

Would you be interested in making a v1 branch in this repo and apply these changes to it, so TIO could you that as the base for v1.

There is also a pull requests I just opened for the changes that TIO needs for v2, this is separate. Can it be merged as well? https://github.com/C0deH4cker/Fission/pull/6

Thank you in advance!

**Comment by C0deH4cker** [comment]
Hi! I can probably get to these in a week or two (I'm quite busy with school and other obligations right now). I actually wasn't aware that people were actually still using Fission. I might pick up this project and add more to it if people still seem interested.

**Comment by C0deH4cker** [comment]
Sorry for the delay, but I've just backported those fixes from Fission 2 to the `v1` branch and released the new version as `1.0.1` (tagged). I've also merged your pull request for Fission 2. Let me know if there's anything else you need me to do to help getting Fission working in TIO!
